// Generated by gonvex dev. Do not edit.

import { control as gonvexControl, type LiveQueryPlan } from "@gonvex/client";

export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };
export type FunctionKind = "query" | "reducer" | "action";
export type OptimisticID = string | readonly string[];
export type OptimisticValue = JsonValue | { readonly $arg: string | readonly string[] } | readonly OptimisticValue[] | { readonly [key: string]: OptimisticValue };
export type OptimisticEffectDefinition =
  | { readonly operation: "patch"; readonly entity: string; readonly id: OptimisticID; readonly fields: Readonly<Record<string, OptimisticValue>> }
  | { readonly operation: "upsert"; readonly entity: string; readonly id: OptimisticID; readonly value: Readonly<Record<string, OptimisticValue>> }
  | { readonly operation: "delete"; readonly entity: string; readonly id: OptimisticID };
export type OptimisticTransactionDefinition = { readonly effects: readonly OptimisticEffectDefinition[]; readonly expectedRevision?: number };
export type FunctionReference<Kind extends FunctionKind = FunctionKind, Args = JsonValue, Result = JsonValue> = {
  readonly kind: Kind;
  readonly path: string;
  readonly delivery?: "oneShot" | "live" | "replica";
  readonly replica?: { readonly table: string; readonly key: string; readonly columns?: readonly string[] };
  readonly offline?: { readonly mode: "forbidden" | "allowed" | "onlineOnly"; readonly conflict?: "reject" | "expectedVersion" | "merge"; readonly reason?: string };
  readonly localExecution?: 1;
  readonly args?: Args;
  readonly result?: Result;
  readonly live?: { readonly entity: string; readonly key: string; readonly resultPath?: readonly string[]; readonly plan: LiveQueryPlan };
  readonly optimistic?: { readonly transaction?: OptimisticTransactionDefinition };
};

export type FilesCreateUploadUrlArgs = {
  contentType: string;
  size?: number | undefined;
};
export type FilesCreateUploadUrlResult = {
  fileId: string;
  url: string;
  method: string;
  headers?: Record<string, string> | undefined;
};
export type FilesDeleteArgs = {
  fileId: string;
};
export type FilesDeleteResult = {
  deleted: boolean;
};
export type FilesGetMetadataArgs = {
  fileId: string;
};
export type FilesGetMetadataResult = Record<string, JsonValue>;
export type FilesGetUrlArgs = {
  fileId: string;
};
export type FilesGetUrlResult = {
  url: string;
};
export type SystemHeartbeatArgs = { };
export type SystemHeartbeatResult = {
  ok: boolean;
};
export type TasksCreateArgs = {
  title: string;
};
export type TasksCreateResult = {
  id: string;
  title: string;
  status: string;
};
export type TasksGridArgs = {
  offset: number;
  limit: number;
  search?: string | undefined;
  sort?: string | undefined;
  direction?: string | undefined;
  filters?: Array<{
  id?: string | undefined;
  column: string;
  operator: string;
  value: string;
  valueTo?: string | undefined;
}> | undefined;
};
export type TasksGridResult = {
  rows: Array<Record<string, JsonValue>>;
  total: number;
  offset: number;
  limit: number;
};
export type TasksListArgs = { };
export type TasksListResult = Array<{
  id: string;
  title: string;
  status: string;
}>;
export type TasksRandomizeStatusPriorityArgs = {
  count: number;
};
export type TasksRandomizeStatusPriorityResult = {
  updated: number;
  requested: number;
  durationMs: number;
};

function lazyReferences<T extends Record<string, () => unknown>>(factories: T): { readonly [Key in keyof T]: ReturnType<T[Key]> } {
  const references = {} as { readonly [Key in keyof T]: ReturnType<T[Key]> };
  for (const key of Object.keys(factories)) {
    const factory = factories[key]!;
    let initialized = false;
    let value: unknown;
    Object.defineProperty(references, key, { enumerable: true, get() {
      if (!initialized) { value = factory(); initialized = true; }
      return value;
    } });
  }
  return references;
}

export const api = /* @__PURE__ */ lazyReferences({
  "files": () => (/* @__PURE__ */ lazyReferences({
    "createUploadUrl": () => ({
      kind: "action",
      path: "files.createUploadUrl",
    } as unknown as FunctionReference<"action", FilesCreateUploadUrlArgs, FilesCreateUploadUrlResult>),
    "delete": () => ({
      kind: "action",
      path: "files.delete",
    } as unknown as FunctionReference<"action", FilesDeleteArgs, FilesDeleteResult>),
    "getMetadata": () => ({
      kind: "action",
      path: "files.getMetadata",
    } as unknown as FunctionReference<"action", FilesGetMetadataArgs, FilesGetMetadataResult>),
    "getUrl": () => ({
      kind: "action",
      path: "files.getUrl",
    } as unknown as FunctionReference<"action", FilesGetUrlArgs, FilesGetUrlResult>),
  })),
  "tasks": () => (/* @__PURE__ */ lazyReferences({
    "create": () => ({
      kind: "reducer",
      offline: {
        mode: "onlineOnly",
        reason: "dashboard data-generator operation",
      },
      path: "tasks.create",
    } as unknown as FunctionReference<"reducer", TasksCreateArgs, TasksCreateResult>),
    "grid": () => ({
      delivery: "live",
      kind: "query",
      live: {
        entity: "dashboard_demo_tasks",
        key: "id",
        plan: {
          columns: ["id","pg_id","name","title","description","form_id","sla_id","approval_id","notes_count","category_icon","category_color","category_name","tag_names","tag_colors","attachment_count","view_count","status","status_name","status_color","status_action","status_icon","status_working_animation","status_initial","priority","priority_name","priority_color","assignee","assignee_names","assignee_ids","assignee_avatar_urls","all_user_names","all_user_avatar_urls","due_date","due_at","start_date","spot_id","spot_name","workspace_name","progress","flag_color","created_at","updated_at"],
          filters: {
            allowedColumns: ["id","pg_id","name","title","description","form_id","sla_id","approval_id","notes_count","category_icon","category_color","category_name","tag_names","tag_colors","attachment_count","view_count","status","status_name","status_color","status_action","status_icon","status_working_animation","status_initial","priority","priority_name","priority_color","assignee","assignee_names","assignee_ids","assignee_avatar_urls","all_user_names","all_user_avatar_urls","due_date","due_at","start_date","spot_id","spot_name","workspace_name","progress","flag_color","created_at","updated_at"],
            allowedOperators: ["contains","notContains","equals","notEquals","startsWith","endsWith","empty","notEmpty","oneOf","lessThan","lessThanOrEqual","greaterThan","greaterThanOrEqual","inRange"],
            argument: "filters",
          },
          key: "id",
          resultPath: ["rows"],
          search: {
            argument: "search",
            columns: ["title","description","status_name","priority_name","assignee_names"],
          },
          sort: {
            allowedColumns: ["created_at","updated_at","due_date","title","status_name","priority_name"],
            columnArgument: "sort",
            defaultColumn: "created_at",
            defaultDirection: "desc",
            directionArgument: "direction",
          },
          table: "dashboard_demo_tasks",
          window: {
            count: "exact",
            defaultLimit: 100,
            limitArgument: "limit",
            maxLimit: 250,
            offsetArgument: "offset",
          },
        },
        resultPath: ["rows"],
      },
      path: "tasks.grid",
    } as unknown as FunctionReference<"query", TasksGridArgs, TasksGridResult>),
    "list": () => ({
      delivery: "replica",
      kind: "query",
      path: "tasks.list",
      replica: {
        columns: ["id","title","status"],
        key: "id",
        maxBytes: 50000000,
        maxRows: 10000,
        mode: "progressive",
        table: "dashboard_demo_tasks",
      },
    } as unknown as FunctionReference<"query", TasksListArgs, TasksListResult>),
    "randomizeStatusPriority": () => ({
      kind: "reducer",
      offline: {
        mode: "onlineOnly",
        reason: "dashboard bulk benchmark operation",
      },
      path: "tasks.randomizeStatusPriority",
    } as unknown as FunctionReference<"reducer", TasksRandomizeStatusPriorityArgs, TasksRandomizeStatusPriorityResult>),
  })),
});

export const control = gonvexControl;

export const internal = /* @__PURE__ */ lazyReferences({
  "system": () => (/* @__PURE__ */ lazyReferences({
    "heartbeat": () => ({
      kind: "reducer",
      offline: {
        mode: "forbidden",
      },
      path: "system.heartbeat",
    } as unknown as FunctionReference<"reducer", SystemHeartbeatArgs, SystemHeartbeatResult>),
  })),
});
export type Api = typeof api;

export const optimisticTransactions: Record<string, OptimisticTransactionDefinition> = {
};

export type ApiArgs = {
  "files.createUploadUrl": FilesCreateUploadUrlArgs;
  "files.delete": FilesDeleteArgs;
  "files.getMetadata": FilesGetMetadataArgs;
  "files.getUrl": FilesGetUrlArgs;
  "system.heartbeat": SystemHeartbeatArgs;
  "tasks.create": TasksCreateArgs;
  "tasks.grid": TasksGridArgs;
  "tasks.list": TasksListArgs;
  "tasks.randomizeStatusPriority": TasksRandomizeStatusPriorityArgs;
};

export type ApiResults = {
  "files.createUploadUrl": FilesCreateUploadUrlResult;
  "files.delete": FilesDeleteResult;
  "files.getMetadata": FilesGetMetadataResult;
  "files.getUrl": FilesGetUrlResult;
  "system.heartbeat": SystemHeartbeatResult;
  "tasks.create": TasksCreateResult;
  "tasks.grid": TasksGridResult;
  "tasks.list": TasksListResult;
  "tasks.randomizeStatusPriority": TasksRandomizeStatusPriorityResult;
};

export function optimisticPatchesFor(
  path: string,
  args: Record<string, unknown>,
): Array<{ entity?: string; collection?: string; rowId: string; op: "patch" | "insert" | "upsert" | "delete"; fields?: Record<string, unknown> }> {
  const transaction = Object.prototype.hasOwnProperty.call(optimisticTransactions, path)
    ? optimisticTransactions[path]
    : undefined;
  if (transaction && Array.isArray(transaction.effects) && transaction.effects.length > 0) {
    const readPath = (value: unknown, segments: readonly string[]): unknown =>
      segments.reduce<unknown>((current, segment) =>
        current && typeof current === "object" ? (current as Record<string, unknown>)[segment] : undefined, value);
    const resolveValue = (value: unknown): unknown => {
      if (Array.isArray(value)) return value.map(resolveValue);
      if (!value || typeof value !== "object") return value;
      const record = value as Record<string, unknown>;
      if (Object.keys(record).length === 1 && Object.prototype.hasOwnProperty.call(record, "$arg")) {
        const path = record.$arg;
        const segments = Array.isArray(path)
          ? path.filter((part): part is string => typeof part === "string" && part.trim().length > 0)
          : typeof path === "string" ? path.split(".").map((part) => part.trim()).filter(Boolean) : [];
        return segments.length > 0 ? readPath(args, segments) : undefined;
      }
      return Object.fromEntries(Object.entries(record).map(([key, item]) => [key, resolveValue(item)]));
    };
    const containsUndefined = (value: unknown): boolean =>
      value === undefined || (Array.isArray(value)
        ? value.some(containsUndefined)
        : !!value && typeof value === "object" && Object.values(value as Record<string, unknown>).some(containsUndefined));
    const patches: Array<{ entity?: string; collection?: string; rowId: string; op: "patch" | "insert" | "upsert" | "delete"; fields?: Record<string, unknown> }> = [];
    for (const effect of transaction.effects) {
      const rawId = Array.isArray(effect.id) ? readPath(args, effect.id) : effect.id;
      const rowId = String(rawId ?? "").trim();
      if (!rowId || !effect.entity) return [];
      if (effect.operation === "delete") {
        patches.push({ entity: effect.entity, rowId, op: "delete" });
        continue;
      }
      const template = effect.operation === "patch" ? effect.fields : effect.value;
      if (!template || typeof template !== "object" || Array.isArray(template)) return [];
      const fields = resolveValue(template);
      if (!fields || typeof fields !== "object" || Array.isArray(fields) || containsUndefined(fields)) return [];
      patches.push({ entity: effect.entity, rowId, op: effect.operation === "upsert" ? "upsert" : "patch", fields: { ...(fields as Record<string, unknown>) } });
    }
    return patches;
  }
  return [];
}
