// Generated by gonvex dev. Do not edit.

import { control as gonvexControl, type LiveQueryPlan } from "@gonvex/client";

export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };
export type FunctionKind = "query" | "reducer" | "action";
export type OptimisticID = string | readonly string[];
export type OptimisticValue = JsonValue | { readonly $arg: string | readonly string[] } | readonly OptimisticValue[] | { readonly [key: string]: OptimisticValue };
export type OptimisticEffectDefinition =
  | { readonly operation: "patch"; readonly entity: string; readonly id: OptimisticID; readonly fields: Readonly<Record<string, OptimisticValue>> }
  | { readonly operation: "upsert"; readonly entity: string; readonly id: OptimisticID; readonly value: Readonly<Record<string, OptimisticValue>> }
  | { readonly operation: "delete"; readonly entity: string; readonly id: OptimisticID };
export type OptimisticTransactionDefinition = { readonly effects: readonly OptimisticEffectDefinition[]; readonly expectedRevision?: number };
export type FunctionReference<Kind extends FunctionKind = FunctionKind, Args = JsonValue, Result = JsonValue> = {
  readonly kind: Kind;
  readonly path: string;
  readonly delivery?: "oneShot" | "live" | "replica";
  readonly offline?: { readonly mode: "forbidden" | "allowed" | "onlineOnly"; readonly conflict?: "reject" | "expectedVersion" | "merge"; readonly reason?: string };
  readonly args?: Args;
  readonly result?: Result;
  readonly live?: { readonly entity: string; readonly key: string; readonly resultPath?: readonly string[]; readonly plan: LiveQueryPlan };
  readonly optimistic?: { readonly transaction?: OptimisticTransactionDefinition };
};

export type FilesCreateUploadUrlArgs = {
  contentType: string;
  size?: number | undefined;
};
export type FilesCreateUploadUrlResult = {
  fileId: string;
  url: string;
  method: string;
  headers?: Record<string, string> | undefined;
};
export type FilesDeleteArgs = {
  fileId: string;
};
export type FilesDeleteResult = {
  deleted: boolean;
};
export type FilesGetMetadataArgs = {
  fileId: string;
};
export type FilesGetMetadataResult = Record<string, JsonValue>;
export type FilesGetUrlArgs = {
  fileId: string;
};
export type FilesGetUrlResult = {
  url: string;
};
export type SystemHeartbeatArgs = { };
export type SystemHeartbeatResult = {
  ok: boolean;
};
export type TasksCreateArgs = {
  title: string;
};
export type TasksCreateResult = {
  id: string;
  title: string;
  status: string;
};
export type TasksGridArgs = {
  offset: number;
  limit: number;
  search?: string | undefined;
  sort?: string | undefined;
  direction?: string | undefined;
  filters?: Array<{
  id?: string | undefined;
  column: string;
  operator: string;
  value: string;
  valueTo?: string | undefined;
}> | undefined;
};
export type TasksGridResult = {
  rows: Array<Record<string, JsonValue>>;
  total: number;
  offset: number;
  limit: number;
};
export type TasksListArgs = { };
export type TasksListResult = Array<{
  id: string;
  title: string;
  status: string;
}>;
export type TasksRandomizeStatusPriorityArgs = {
  count: number;
};
export type TasksRandomizeStatusPriorityResult = {
  updated: number;
  requested: number;
  durationMs: number;
};

export const api = {
  files: {
    createUploadUrl: {
      args: {
        fields: {
          contentType: {
            kind: "string",
          },
          size: {
            kind: "optional",
            value: {
              integer: true,
              kind: "number",
            },
          },
        },
        kind: "object",
      },
      kind: "action",
      path: "files.createUploadUrl",
      result: {
        fields: {
          fileId: {
            kind: "string",
          },
          headers: {
            kind: "optional",
            value: {
              kind: "record",
              values: {
                kind: "string",
              },
            },
          },
          method: {
            kind: "string",
          },
          url: {
            kind: "string",
          },
        },
        kind: "object",
      },
    } as unknown as FunctionReference<"action", FilesCreateUploadUrlArgs, FilesCreateUploadUrlResult>,
    delete: {
      args: {
        fields: {
          fileId: {
            kind: "string",
          },
        },
        kind: "object",
      },
      kind: "action",
      path: "files.delete",
      result: {
        fields: {
          deleted: {
            kind: "boolean",
          },
        },
        kind: "object",
      },
    } as unknown as FunctionReference<"action", FilesDeleteArgs, FilesDeleteResult>,
    getMetadata: {
      args: {
        fields: {
          fileId: {
            kind: "string",
          },
        },
        kind: "object",
      },
      kind: "action",
      path: "files.getMetadata",
      result: {
        kind: "record",
        values: {
          kind: "any",
        },
      },
    } as unknown as FunctionReference<"action", FilesGetMetadataArgs, FilesGetMetadataResult>,
    getUrl: {
      args: {
        fields: {
          fileId: {
            kind: "string",
          },
        },
        kind: "object",
      },
      kind: "action",
      path: "files.getUrl",
      result: {
        fields: {
          url: {
            kind: "string",
          },
        },
        kind: "object",
      },
    } as unknown as FunctionReference<"action", FilesGetUrlArgs, FilesGetUrlResult>,
  },
  tasks: {
    create: {
      args: {
        fields: {
          title: {
            kind: "string",
          },
        },
        kind: "object",
      },
      kind: "reducer",
      offline: {
        mode: "onlineOnly",
        reason: "dashboard data-generator operation",
      },
      path: "tasks.create",
      result: {
        fields: {
          id: {
            entity: "dashboard_demo_tasks",
            kind: "id",
          },
          status: {
            kind: "string",
          },
          title: {
            kind: "string",
          },
        },
        kind: "object",
      },
    } as unknown as FunctionReference<"reducer", TasksCreateArgs, TasksCreateResult>,
    grid: {
      args: {
        fields: {
          direction: {
            kind: "optional",
            value: {
              kind: "string",
            },
          },
          filters: {
            kind: "optional",
            value: {
              items: {
                fields: {
                  column: {
                    kind: "string",
                  },
                  id: {
                    kind: "optional",
                    value: {
                      kind: "string",
                    },
                  },
                  operator: {
                    kind: "string",
                  },
                  value: {
                    kind: "string",
                  },
                  valueTo: {
                    kind: "optional",
                    value: {
                      kind: "string",
                    },
                  },
                },
                kind: "object",
              },
              kind: "array",
            },
          },
          limit: {
            integer: true,
            kind: "number",
          },
          offset: {
            integer: true,
            kind: "number",
          },
          search: {
            kind: "optional",
            value: {
              kind: "string",
            },
          },
          sort: {
            kind: "optional",
            value: {
              kind: "string",
            },
          },
        },
        kind: "object",
      },
      delivery: "live",
      kind: "query",
      live: {
        entity: "dashboard_demo_tasks",
        key: "id",
        plan: {
          columns: ["id","pg_id","name","title","description","form_id","sla_id","approval_id","notes_count","category_icon","category_color","category_name","tag_names","tag_colors","attachment_count","view_count","status","status_name","status_color","status_action","status_icon","status_working_animation","status_initial","priority","priority_name","priority_color","assignee","assignee_names","assignee_ids","assignee_avatar_urls","all_user_names","all_user_avatar_urls","due_date","due_at","start_date","spot_id","spot_name","workspace_name","progress","flag_color","created_at","updated_at"],
          filters: {
            allowedColumns: ["id","pg_id","name","title","description","form_id","sla_id","approval_id","notes_count","category_icon","category_color","category_name","tag_names","tag_colors","attachment_count","view_count","status","status_name","status_color","status_action","status_icon","status_working_animation","status_initial","priority","priority_name","priority_color","assignee","assignee_names","assignee_ids","assignee_avatar_urls","all_user_names","all_user_avatar_urls","due_date","due_at","start_date","spot_id","spot_name","workspace_name","progress","flag_color","created_at","updated_at"],
            allowedOperators: ["contains","notContains","equals","notEquals","startsWith","endsWith","empty","notEmpty","oneOf","lessThan","lessThanOrEqual","greaterThan","greaterThanOrEqual","inRange"],
            argument: "filters",
          },
          key: "id",
          resultPath: ["rows"],
          search: {
            argument: "search",
            columns: ["title","description","status_name","priority_name","assignee_names"],
          },
          sort: {
            allowedColumns: ["created_at","updated_at","due_date","title","status_name","priority_name"],
            columnArgument: "sort",
            defaultColumn: "created_at",
            defaultDirection: "desc",
            directionArgument: "direction",
          },
          table: "dashboard_demo_tasks",
          window: {
            count: "exact",
            defaultLimit: 100,
            limitArgument: "limit",
            maxLimit: 250,
            offsetArgument: "offset",
          },
        },
        resultPath: ["rows"],
      },
      path: "tasks.grid",
      result: {
        fields: {
          limit: {
            integer: true,
            kind: "number",
          },
          offset: {
            integer: true,
            kind: "number",
          },
          rows: {
            items: {
              kind: "record",
              values: {
                kind: "any",
              },
            },
            kind: "array",
          },
          total: {
            integer: true,
            kind: "number",
          },
        },
        kind: "object",
      },
    } as unknown as FunctionReference<"query", TasksGridArgs, TasksGridResult>,
    list: {
      args: {
        fields: {
        },
        kind: "object",
      },
      delivery: "replica",
      kind: "query",
      path: "tasks.list",
      result: {
        items: {
          fields: {
            id: {
              entity: "dashboard_demo_tasks",
              kind: "id",
            },
            status: {
              kind: "string",
            },
            title: {
              kind: "string",
            },
          },
          kind: "object",
        },
        kind: "array",
      },
    } as unknown as FunctionReference<"query", TasksListArgs, TasksListResult>,
    randomizeStatusPriority: {
      args: {
        fields: {
          count: {
            integer: true,
            kind: "number",
          },
        },
        kind: "object",
      },
      kind: "reducer",
      offline: {
        mode: "onlineOnly",
        reason: "dashboard bulk benchmark operation",
      },
      path: "tasks.randomizeStatusPriority",
      result: {
        fields: {
          durationMs: {
            integer: true,
            kind: "number",
          },
          requested: {
            integer: true,
            kind: "number",
          },
          updated: {
            integer: true,
            kind: "number",
          },
        },
        kind: "object",
      },
    } as unknown as FunctionReference<"reducer", TasksRandomizeStatusPriorityArgs, TasksRandomizeStatusPriorityResult>,
  },
} as const;

export const control = gonvexControl;

export const internal = {
  system: {
    heartbeat: {
      args: {
        fields: {
        },
        kind: "object",
      },
      kind: "reducer",
      path: "system.heartbeat",
      result: {
        fields: {
          ok: {
            kind: "boolean",
          },
        },
        kind: "object",
      },
    } as unknown as FunctionReference<"reducer", SystemHeartbeatArgs, SystemHeartbeatResult>,
  },
} as const;
export type Api = typeof api;

export const optimisticTransactions: Record<string, OptimisticTransactionDefinition> = {
};

export type ApiArgs = {
  "files.createUploadUrl": FilesCreateUploadUrlArgs;
  "files.delete": FilesDeleteArgs;
  "files.getMetadata": FilesGetMetadataArgs;
  "files.getUrl": FilesGetUrlArgs;
  "system.heartbeat": SystemHeartbeatArgs;
  "tasks.create": TasksCreateArgs;
  "tasks.grid": TasksGridArgs;
  "tasks.list": TasksListArgs;
  "tasks.randomizeStatusPriority": TasksRandomizeStatusPriorityArgs;
};

export type ApiResults = {
  "files.createUploadUrl": FilesCreateUploadUrlResult;
  "files.delete": FilesDeleteResult;
  "files.getMetadata": FilesGetMetadataResult;
  "files.getUrl": FilesGetUrlResult;
  "system.heartbeat": SystemHeartbeatResult;
  "tasks.create": TasksCreateResult;
  "tasks.grid": TasksGridResult;
  "tasks.list": TasksListResult;
  "tasks.randomizeStatusPriority": TasksRandomizeStatusPriorityResult;
};

export function optimisticPatchesFor(
  path: string,
  args: Record<string, unknown>,
): Array<{ entity?: string; collection?: string; rowId: string; op: "patch" | "insert" | "upsert" | "delete"; fields?: Record<string, unknown> }> {
  const transaction = Object.prototype.hasOwnProperty.call(optimisticTransactions, path)
    ? optimisticTransactions[path]
    : undefined;
  if (transaction && Array.isArray(transaction.effects) && transaction.effects.length > 0) {
    const readPath = (value: unknown, segments: readonly string[]): unknown =>
      segments.reduce<unknown>((current, segment) =>
        current && typeof current === "object" ? (current as Record<string, unknown>)[segment] : undefined, value);
    const resolveValue = (value: unknown): unknown => {
      if (Array.isArray(value)) return value.map(resolveValue);
      if (!value || typeof value !== "object") return value;
      const record = value as Record<string, unknown>;
      if (Object.keys(record).length === 1 && Object.prototype.hasOwnProperty.call(record, "$arg")) {
        const path = record.$arg;
        const segments = Array.isArray(path)
          ? path.filter((part): part is string => typeof part === "string" && part.trim().length > 0)
          : typeof path === "string" ? path.split(".").map((part) => part.trim()).filter(Boolean) : [];
        return segments.length > 0 ? readPath(args, segments) : undefined;
      }
      return Object.fromEntries(Object.entries(record).map(([key, item]) => [key, resolveValue(item)]));
    };
    const containsUndefined = (value: unknown): boolean =>
      value === undefined || (Array.isArray(value)
        ? value.some(containsUndefined)
        : !!value && typeof value === "object" && Object.values(value as Record<string, unknown>).some(containsUndefined));
    const patches: Array<{ entity?: string; collection?: string; rowId: string; op: "patch" | "insert" | "upsert" | "delete"; fields?: Record<string, unknown> }> = [];
    for (const effect of transaction.effects) {
      const rawId = Array.isArray(effect.id) ? readPath(args, effect.id) : effect.id;
      const rowId = String(rawId ?? "").trim();
      if (!rowId || !effect.entity) return [];
      if (effect.operation === "delete") {
        patches.push({ entity: effect.entity, rowId, op: "delete" });
        continue;
      }
      const template = effect.operation === "patch" ? effect.fields : effect.value;
      if (!template || typeof template !== "object" || Array.isArray(template)) return [];
      const fields = resolveValue(template);
      if (!fields || typeof fields !== "object" || Array.isArray(fields) || containsUndefined(fields)) return [];
      patches.push({ entity: effect.entity, rowId, op: effect.operation === "upsert" ? "upsert" : "patch", fields: { ...(fields as Record<string, unknown>) } });
    }
    return patches;
  }
  return [];
}
