// Generated by gonvex dev. Do not edit.

import { control as gonvexControl, type LiveQueryPlan } from "@gonvex/client";

export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };
export type FunctionKind = "query" | "reducer" | "action";
export type OptimisticID = string | readonly string[];
export type OptimisticValue = JsonValue | { readonly $arg: string | readonly string[] } | readonly OptimisticValue[] | { readonly [key: string]: OptimisticValue };
export type OptimisticEffectDefinition =
  | { readonly operation: "patch"; readonly entity: string; readonly id: OptimisticID; readonly fields: Readonly<Record<string, OptimisticValue>> }
  | { readonly operation: "upsert"; readonly entity: string; readonly id: OptimisticID; readonly value: Readonly<Record<string, OptimisticValue>> }
  | { readonly operation: "delete"; readonly entity: string; readonly id: OptimisticID };
export type OptimisticTransactionDefinition = { readonly effects: readonly OptimisticEffectDefinition[]; readonly expectedRevision?: number };
export type FunctionReference<Kind extends FunctionKind = FunctionKind, Args = JsonValue, Result = JsonValue> = {
  readonly kind: Kind;
  readonly path: string;
  readonly delivery?: "oneShot" | "live" | "replica";
  readonly offline?: { readonly mode: "forbidden" | "allowed" | "onlineOnly"; readonly conflict?: "reject" | "expectedVersion" | "merge"; readonly reason?: string };
  readonly args?: Args;
  readonly result?: Result;
  readonly live?: { readonly entity: string; readonly key: string; readonly resultPath?: readonly string[]; readonly plan: LiveQueryPlan };
  readonly optimistic?: { readonly transaction?: OptimisticTransactionDefinition };
};

export type MessagesAgentInvokeArgs = {
  path: string;
  args: JsonValue;
  artifactHash: string;
};
export type MessagesAgentInvokeResult = JsonValue;
export type MessagesEchoArgs = {
  message: string;
};
export type MessagesEchoResult = {
  message: string;
};
export type MessagesGetArgs = {
  id: string;
};
export type MessagesGetResult = Array<{
  id: string;
  body: string;
  author: string;
  created_at: string;
}>;
export type MessagesListArgs = { };
export type MessagesListResult = Array<{
  id: string;
  body: string;
  author: string;
  created_at: string;
}>;
export type MessagesSendArgs = {
  body: string;
};
export type MessagesSendResult = {
  id: string;
  body: string;
  author: string;
  created_at: string;
};

export const api = {
  messages: {
    agentInvoke: {
      args: {
        fields: {
          args: {
            kind: "any",
          },
          artifactHash: {
            kind: "string",
          },
          path: {
            kind: "string",
          },
        },
        kind: "object",
      },
      kind: "action",
      path: "messages.agentInvoke",
      result: {
        kind: "any",
      },
    } as unknown as FunctionReference<"action", MessagesAgentInvokeArgs, MessagesAgentInvokeResult>,
    echo: {
      args: {
        fields: {
          message: {
            kind: "string",
          },
        },
        kind: "object",
      },
      kind: "action",
      path: "messages.echo",
      result: {
        fields: {
          message: {
            kind: "string",
          },
        },
        kind: "object",
      },
    } as unknown as FunctionReference<"action", MessagesEchoArgs, MessagesEchoResult>,
    get: {
      args: {
        fields: {
          id: {
            entity: "messages",
            kind: "id",
          },
        },
        kind: "object",
      },
      delivery: "oneShot",
      kind: "query",
      path: "messages.get",
      result: {
        items: {
          fields: {
            author: {
              kind: "string",
            },
            body: {
              kind: "string",
            },
            created_at: {
              format: "datetime",
              kind: "string",
            },
            id: {
              entity: "messages",
              kind: "id",
            },
          },
          kind: "object",
        },
        kind: "array",
      },
    } as unknown as FunctionReference<"query", MessagesGetArgs, MessagesGetResult>,
    list: {
      args: {
        fields: {
        },
        kind: "object",
      },
      delivery: "live",
      kind: "query",
      live: {
        entity: "messages",
        key: "id",
        plan: {
          columns: ["id","body","author","created_at"],
          key: "id",
          sort: {
            allowedColumns: ["created_at"],
            columnArgument: undefined,
            defaultColumn: "created_at",
            defaultDirection: "asc",
            directionArgument: undefined,
          },
          table: "messages",
        },
        resultPath: [],
      },
      path: "messages.list",
      result: {
        items: {
          fields: {
            author: {
              kind: "string",
            },
            body: {
              kind: "string",
            },
            created_at: {
              format: "datetime",
              kind: "string",
            },
            id: {
              entity: "messages",
              kind: "id",
            },
          },
          kind: "object",
        },
        kind: "array",
      },
    } as unknown as FunctionReference<"query", MessagesListArgs, MessagesListResult>,
    send: {
      args: {
        fields: {
          body: {
            kind: "string",
          },
        },
        kind: "object",
      },
      kind: "reducer",
      offline: {
        mode: "onlineOnly",
        reason: "server assigns the message id",
      },
      path: "messages.send",
      result: {
        fields: {
          author: {
            kind: "string",
          },
          body: {
            kind: "string",
          },
          created_at: {
            format: "datetime",
            kind: "string",
          },
          id: {
            entity: "messages",
            kind: "id",
          },
        },
        kind: "object",
      },
    } as unknown as FunctionReference<"reducer", MessagesSendArgs, MessagesSendResult>,
  },
} as const;

export const control = gonvexControl;

export const internal = {
} as const;
export type Api = typeof api;

export const optimisticTransactions: Record<string, OptimisticTransactionDefinition> = {
};

export type ApiArgs = {
  "messages.agentInvoke": MessagesAgentInvokeArgs;
  "messages.echo": MessagesEchoArgs;
  "messages.get": MessagesGetArgs;
  "messages.list": MessagesListArgs;
  "messages.send": MessagesSendArgs;
};

export type ApiResults = {
  "messages.agentInvoke": MessagesAgentInvokeResult;
  "messages.echo": MessagesEchoResult;
  "messages.get": MessagesGetResult;
  "messages.list": MessagesListResult;
  "messages.send": MessagesSendResult;
};

export function optimisticPatchesFor(
  path: string,
  args: Record<string, unknown>,
): Array<{ entity?: string; collection?: string; rowId: string; op: "patch" | "insert" | "upsert" | "delete"; fields?: Record<string, unknown> }> {
  const transaction = Object.prototype.hasOwnProperty.call(optimisticTransactions, path)
    ? optimisticTransactions[path]
    : undefined;
  if (transaction && Array.isArray(transaction.effects) && transaction.effects.length > 0) {
    const readPath = (value: unknown, segments: readonly string[]): unknown =>
      segments.reduce<unknown>((current, segment) =>
        current && typeof current === "object" ? (current as Record<string, unknown>)[segment] : undefined, value);
    const resolveValue = (value: unknown): unknown => {
      if (Array.isArray(value)) return value.map(resolveValue);
      if (!value || typeof value !== "object") return value;
      const record = value as Record<string, unknown>;
      if (Object.keys(record).length === 1 && Object.prototype.hasOwnProperty.call(record, "$arg")) {
        const path = record.$arg;
        const segments = Array.isArray(path)
          ? path.filter((part): part is string => typeof part === "string" && part.trim().length > 0)
          : typeof path === "string" ? path.split(".").map((part) => part.trim()).filter(Boolean) : [];
        return segments.length > 0 ? readPath(args, segments) : undefined;
      }
      return Object.fromEntries(Object.entries(record).map(([key, item]) => [key, resolveValue(item)]));
    };
    const containsUndefined = (value: unknown): boolean =>
      value === undefined || (Array.isArray(value)
        ? value.some(containsUndefined)
        : !!value && typeof value === "object" && Object.values(value as Record<string, unknown>).some(containsUndefined));
    const patches: Array<{ entity?: string; collection?: string; rowId: string; op: "patch" | "insert" | "upsert" | "delete"; fields?: Record<string, unknown> }> = [];
    for (const effect of transaction.effects) {
      const rawId = Array.isArray(effect.id) ? readPath(args, effect.id) : effect.id;
      const rowId = String(rawId ?? "").trim();
      if (!rowId || !effect.entity) return [];
      if (effect.operation === "delete") {
        patches.push({ entity: effect.entity, rowId, op: "delete" });
        continue;
      }
      const template = effect.operation === "patch" ? effect.fields : effect.value;
      if (!template || typeof template !== "object" || Array.isArray(template)) return [];
      const fields = resolveValue(template);
      if (!fields || typeof fields !== "object" || Array.isArray(fields) || containsUndefined(fields)) return [];
      patches.push({ entity: effect.entity, rowId, op: effect.operation === "upsert" ? "upsert" : "patch", fields: { ...(fields as Record<string, unknown>) } });
    }
    return patches;
  }
  return [];
}
