// Generated by gonvex dev. Do not edit.
export { GonvexClient, createFirebaseAuthAdapter } from "@gonvex/client";
export type { GonvexExternalAuthAdapter, GonvexExternalIdentityHint, GonvexFirebaseAuthAdapterOptions } from "@gonvex/client";
