// Generated by Gonvex. Do not edit.
export declare const artifactHash: "1666ecc0e015aa3e7a6019391e3e512d2cb37223ed4c5763e290d5994b56a22d";
export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };
export type Id<Entity extends string> = string & { readonly __gonvexEntity: Entity };
export interface GonvexAgentAPI {
  "messages.echo": {
    kind: "action";
    classification: "interactive";
    interactive: true;
    args: {
      message: string;
    };
    result: {
      message: string;
    };
    offline: null;
    optimistic: null;
    description: "Return the supplied message without changing durable state.";
    tags: readonly ["messages"];
    confirmation: "none";
  };
  "messages.get": {
    kind: "query";
    classification: "interactive";
    interactive: true;
    args: {
      id: Id<"messages">;
    };
    result: Array<{
      author: string;
      body: string;
      created_at: string;
      id: Id<"messages">;
    }>;
    offline: null;
    optimistic: null;
    description: "Read one visible message by ID.";
    tags: readonly ["messages"];
    confirmation: "none";
  };
  "messages.list": {
    kind: "query";
    classification: "interactive";
    interactive: true;
    args: Record<string, never>;
    result: Array<{
      author: string;
      body: string;
      created_at: string;
      id: Id<"messages">;
    }>;
    offline: null;
    optimistic: null;
    description: "";
    tags: readonly [];
    confirmation: "none";
  };
  "messages.send": {
    kind: "reducer";
    classification: "interactive";
    interactive: true;
    args: {
      body: string;
    };
    result: {
      author: string;
      body: string;
      created_at: string;
      id: Id<"messages">;
    };
    offline: { readonly mode: "onlineOnly"; readonly reason: "server assigns the message id"; };
    optimistic: null;
    description: "Send a message as the acting tenant member.";
    tags: readonly ["messages"];
    confirmation: "none";
  };
}
