import type { JsonValue, ModuleArtifact, ModuleFunction, ModuleSchema } from "./manifest-types.js";

export type FunctionCatalogFormat = "ndjson" | "typescript";

export type FunctionCatalogEntry = {
  path: string;
  kind: ModuleFunction["kind"];
  artifactHash: string;
  args: ModuleSchema;
  result: ModuleSchema;
  classification: "interactive";
  interactive: true;
  offline: JsonValue | null;
  optimistic: JsonValue | null;
  description: string;
  tags: string[];
  confirmation: "none" | "required" | "destructive";
};

const compareText = (left: string, right: string) => left < right ? -1 : left > right ? 1 : 0;

export function functionCatalogEntries(artifact: ModuleArtifact): FunctionCatalogEntry[] {
  return Object.entries(artifact.functions)
    .filter(([, definition]) => !definition.internal && (
      definition.classification === "interactive" || (
        definition.classification === undefined
        && (definition.interactive === true || (definition.interactive === undefined && definition.kind !== "action"))
      )
    ))
    .sort(([left], [right]) => compareText(left, right))
    .map(([path, definition]) => ({
      path,
      kind: definition.kind,
      artifactHash: artifact.hash,
      args: definition.args ?? { kind: "object", fields: {} },
      result: definition.result ?? { kind: "any" },
      classification: "interactive",
      interactive: true,
      offline: definition.offline ?? null,
      optimistic: definition.optimistic ?? null,
      description: definition.description ?? "",
      tags: [...(definition.agent?.tags ?? [])].sort(),
      confirmation: definition.agent?.confirmation ?? "none",
    }));
}

export function renderFunctionCatalog(artifact: ModuleArtifact, format: FunctionCatalogFormat): string {
  const entries = functionCatalogEntries(artifact);
  if (format === "ndjson") {
    return entries.map((entry) => JSON.stringify(entry)).join("\n") + (entries.length > 0 ? "\n" : "");
  }
  const lines = [
    "// Generated by Gonvex. Do not edit.",
    `export declare const artifactHash: ${JSON.stringify(artifact.hash)};`,
    "export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };",
    "export type Id<Entity extends string> = string & { readonly __gonvexEntity: Entity };",
    "export interface GonvexAgentAPI {",
  ];
  for (const entry of entries) {
    lines.push(`  ${JSON.stringify(entry.path)}: {`);
    lines.push(`    kind: ${JSON.stringify(entry.kind)};`);
    lines.push('    classification: "interactive";');
    lines.push("    interactive: true;");
    lines.push(`    args: ${renderPortableSchema(entry.args, 4)};`);
    lines.push(`    result: ${renderPortableSchema(entry.result, 4)};`);
    lines.push(`    offline: ${renderJsonLiteralType(entry.offline)};`);
    lines.push(`    optimistic: ${renderJsonLiteralType(entry.optimistic)};`);
    lines.push(`    description: ${JSON.stringify(entry.description)};`);
    lines.push(`    tags: readonly [${entry.tags.map((tag) => JSON.stringify(tag)).join(", ")}];`);
    lines.push(`    confirmation: ${JSON.stringify(entry.confirmation)};`);
    lines.push("  };");
  }
  lines.push("}", "");
  return lines.join("\n");
}

export function renderPortableSchema(schema: ModuleSchema, indent = 0): string {
  if (!schema || typeof schema !== "object" || Array.isArray(schema)) return "unknown";
  const value = schema as Record<string, unknown>;
  switch (value.kind) {
    case "string": return "string";
    case "number": return "number";
    case "boolean": return "boolean";
    case "null": return "null";
    case "any": return "JsonValue";
    case "id": return `Id<${JSON.stringify(String(value.entity ?? ""))}>`;
    case "literal": return renderLiteral(value.value as JsonValue);
    case "array": return `Array<${renderPortableSchema(value.items as ModuleSchema, indent)}>`;
    case "record": return `Record<string, ${renderPortableSchema(value.values as ModuleSchema, indent)}>`;
    case "optional": return `${renderPortableSchema(value.value as ModuleSchema, indent)} | undefined`;
    case "object": {
      const fields = value.fields && typeof value.fields === "object" && !Array.isArray(value.fields)
        ? Object.entries(value.fields as Record<string, ModuleSchema>).sort(([left], [right]) => compareText(left, right))
        : [];
      if (fields.length === 0) return "Record<string, never>";
      const padding = " ".repeat(indent);
      const childPadding = " ".repeat(indent + 2);
      const rendered = fields.map(([name, field]) => {
        const optional = field?.kind === "optional";
        const actual = field.kind === "optional" ? field.value : field;
        return `${childPadding}${renderProperty(name)}${optional ? "?" : ""}: ${renderPortableSchema(actual, indent + 2)};`;
      });
      if (value.allowUnknown === true) rendered.push(`${childPadding}[key: string]: JsonValue;`);
      return `{\n${rendered.join("\n")}\n${padding}}`;
    }
    default: return "unknown";
  }
}

function renderProperty(value: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(value) ? value : JSON.stringify(value);
}

function renderLiteral(value: JsonValue): string {
  if (value === null || typeof value === "boolean" || typeof value === "number" || typeof value === "string") {
    return JSON.stringify(value);
  }
  return "JsonValue";
}

function renderJsonLiteralType(value: JsonValue): string {
  if (value === null || typeof value === "boolean" || typeof value === "number" || typeof value === "string") {
    return JSON.stringify(value);
  }
  if (Array.isArray(value)) {
    return `readonly [${value.map(renderJsonLiteralType).join(", ")}]`;
  }
  const fields = Object.entries(value)
    .sort(([left], [right]) => compareText(left, right))
    .map(([name, field]) => `readonly ${renderProperty(name)}: ${renderJsonLiteralType(field)};`);
  return `{ ${fields.join(" ")} }`;
}
