import { rolldown } from "rolldown";
import { createHash } from "node:crypto";
import { readFile, readdir, writeFile, mkdir } from "node:fs/promises";
import { dirname, join, relative, resolve } from "node:path";
import { compileLocalSchema, type LocalSchema } from "@gonvex/local-runtime/schema";
import type { Manifest } from "./manifest-types.js";

export async function projectLocalSchema(root: string): Promise<LocalSchema> {
  const migrationDirectory = join(root, "migrations");
  const names = (await readdir(migrationDirectory).catch(() => [] as string[])).filter((name) => name.endsWith(".sql")).sort();
  const migrations = await Promise.all(names.map(async (name) => ({ name, sql: await readFile(join(migrationDirectory, name), "utf8") })));
  const tenantMigrations = migrations.filter(({ sql }) => !/gonvex:scope\s+(control|landlord)/.test(sql));
  const digest = createHash("sha256").update("local-schema-v1").update(JSON.stringify(tenantMigrations)).digest("hex");
  const cacheFile = join(root, "gonvex", "_build", `local-schema-${digest}.json`);
  let schema: LocalSchema;
  try { schema = JSON.parse(await readFile(cacheFile, "utf8")) as LocalSchema; }
  catch {
    schema = await compileLocalSchema(tenantMigrations);
    await mkdir(dirname(cacheFile), { recursive: true });
    await writeFile(cacheFile, JSON.stringify(schema));
  }
  return schema;
}

export async function localBindings(root: string, manifest: Manifest): Promise<Record<string, string>> {
  const reducers = Object.entries(manifest.functions).filter(([, entry]) => entry.localExecution === 1);
  if (!reducers.length) return {};
  const schema = await projectLocalSchema(root);
  const generatedDirectory = join(root, "gonvex", "_generated");
  const imports = reducers.map(([, entry], index) => {
    let file = relative(generatedDirectory, resolve(root, entry.file)).replaceAll("\\", "/").replace(/\.(?:tsx?|mts|cts)$/, ".js");
    if (!file.startsWith(".")) file = `./${file}`;
    return `import { ${entry.handler} as reducer${index} } from ${JSON.stringify(file)};`;
  });
  const entryFile = join(root, "gonvex", "_build", "local-entry.ts");
  await mkdir(dirname(entryFile), { recursive: true });
  await writeFile(entryFile, `${imports.join("\n")}\nexport const localReducers = {${reducers.map(([path], index) => `${JSON.stringify(path)}: reducer${index}`).join(",")}};`);
  const bundle = await rolldown({
    input: entryFile, cwd: root, platform: "browser", tsconfig: false,
    treeshake: { manualPureFunctions: ["action", "internalReducer", "query", "liveQuery", "replicaCollection", "visibility"] },
    resolve: { conditionNames: ["browser", "import", "default"], mainFields: ["browser", "module", "main"] },
  });
  let localCode: string;
  try {
    const output = await bundle.generate({ format: "esm", codeSplitting: false });
    if (output.output.length !== 1 || output.output[0]?.type !== "chunk") throw new Error("Local Reducers must compile into one self-contained module");
    localCode = output.output[0].code;
  } finally { await bundle.close(); }
  const contractBytes = manifest.module.files["client-contract.json"];
  const clientContract = contractBytes ? JSON.parse(Buffer.from(contractBytes, "base64").toString()) : undefined;
  const header = "// Generated by Gonvex. Do not edit.\n";
  return {
    "local-schema.ts": `${header}export const localSchema = ${JSON.stringify(schema)} as const;\n`,
    "local-reducers.js": header + localCode,
    "local-reducers.d.ts": `${header}import type { ReducerDefinition } from "@gonvex/module-sdk";\nexport declare const localReducers: Readonly<Record<string, ReducerDefinition<any, any>>>;\n`,
    "local-worker.ts": `${header}import { serveLocalReducerWorker } from "@gonvex/local-runtime/worker";\nimport { localSchema } from "./local-schema.js";\nimport { localReducers } from "./local-reducers.js";\nserveLocalReducerWorker({ schema: localSchema, reducers: localReducers, artifactHash: ${JSON.stringify(manifest.module.hash)} });\n`,
    "local-runtime.ts": `${header}import { createLocalReducerWorker } from "@gonvex/local-runtime/worker-client";\nexport const localRuntime = { clientContract: ${JSON.stringify(clientContract)}, artifactHash: ${JSON.stringify(manifest.module.hash)}, tables: ${JSON.stringify(Object.keys(schema))}, collections: ${JSON.stringify(Object.entries(manifest.functions).filter(([path]) => path.startsWith("__local.")).map(([path, entry]) => ({kind:"query", path, delivery:"replica", replica:entry.replica})))} as const, create: () => createLocalReducerWorker(new Worker(new URL("./local-worker.ts", import.meta.url), { type: "module" })) };\n`,
  };
}
