/** Native JS executes the same portable reducer body against SDK storage. */
export async function nativeLocalBindings(_root: string, _localCode: string, _schema: unknown, _metadata: Record<string, unknown>): Promise<Record<string,string>> {
  const header = "// Generated by Gonvex. Do not edit.\n";
  const client = `${header}import {GonvexClient as BaseClient, type GonvexClientOptions} from "@gonvex/client";
import {localRuntime} from "./local-runtime";
export class GonvexClient extends BaseClient {constructor(url:string, options:GonvexClientOptions={}) {super(url,{...options,localRuntime:options.localRuntime??localRuntime});}}
export {createFirebaseAuthAdapter} from "@gonvex/client";\n`;
  return {
    "client.native.ts": client,
    "client.web.ts": client,
    "local-native-host.json": "{}\n",
    "local-native-binding.ts": `${header}export {localRuntime} from "./local-executor";\n`,
    "local-runtime.native.tsx": `${header}import {installNativeRuntimeGlobals} from "@gonvex/local-runtime/native-bridge";
import * as ExpoCrypto from "expo-crypto";
installNativeRuntimeGlobals({getRandomValues:array=>ExpoCrypto.getRandomValues(array),randomUUID:ExpoCrypto.randomUUID,digest:data=>ExpoCrypto.digest(ExpoCrypto.CryptoDigestAlgorithm.SHA256,data)});
export {localRuntime} from "./local-executor";
export function LocalRuntimeHost() { return null; }\n`,
    "local-runtime.web.tsx": `${header}export {localRuntime} from "./local-executor";
export function LocalRuntimeHost() { return null; }\n`,
  };
}
