import { rolldown } from 'rolldown';
import { createRequire } from 'node:module';
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';

/** Package the same PostgreSQL host and reducer body for WebViews with no runtime downloads. */
export async function nativeLocalBindings(root: string, localCode: string, schema: unknown, metadata: Record<string, unknown>): Promise<Record<string,string>> {
  const require = createRequire(import.meta.url);
  const worker = require.resolve('@gonvex/local-runtime/worker');
  const pglite = dirname(createRequire(worker).resolve('@electric-sql/pglite'));
  const assets = await Promise.all(['pglite.wasm','initdb.wasm','pglite.data'].map(name => readFile(join(pglite,name))));
  const buildDir = join(root,'gonvex','_build');
  const reducers = join(buildDir,'native-reducers.js');
  await writeFile(reducers,localCode);
  const entry = join(buildDir,'native-host.ts');
  await writeFile(entry, `import {serveLocalReducerWorker} from ${JSON.stringify(worker)};
import {localReducers} from './native-reducers.js';
const send = (message) => {
 const encoded = JSON.stringify(message, (_key,value) => value instanceof Error ? {name:value.name,message:value.message} : value);
 if (window.ReactNativeWebView) window.ReactNativeWebView.postMessage(encoded);
 else window.parent.postMessage(encoded,'*');
};
window.postMessage = send;
const bytes = encoded => Uint8Array.from(atob(encoded), c=>c.charCodeAt(0));
(async()=>{
 const [pgliteWasmModule,initdbWasmModule] = await Promise.all([WebAssembly.compile(bytes(${JSON.stringify(assets[0]!.toString('base64'))})),WebAssembly.compile(bytes(${JSON.stringify(assets[1]!.toString('base64'))}))]);
 serveLocalReducerWorker({schema:${JSON.stringify(schema)},reducers:localReducers,artifactHash:${JSON.stringify(metadata.artifactHash)},engine:{pgliteWasmModule,initdbWasmModule,fsBundle:new Blob([bytes(${JSON.stringify(assets[2]!.toString('base64'))})])}});
})().catch(error=>send({id:0,error:{name:error.name,message:error.message}}));`);
  const bundle = await rolldown({input:entry,platform:'browser',tsconfig:false,transform:{define:{'import.meta.url':JSON.stringify('https://gonvex.local.invalid/runtime.js')}},resolve:{conditionNames:['browser','import','default']}});
  let code: string;
  try {
    const output = await bundle.generate({format:'iife',codeSplitting:false});
    if(output.output.length!==1 || output.output[0]?.type!=='chunk')throw Error('Native reducer host must be self-contained');
    code=output.output[0].code;
  } finally { await bundle.close(); }
  const html = `<!doctype html><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'unsafe-inline' 'unsafe-eval'; style-src 'unsafe-inline'; connect-src 'none'"><script>${code.replace(/<\/script/gi,'<\\/script')}</script>`;
  const header = '// Generated by Gonvex. Do not edit.\n';
  const shared = `${header}import {nativeReducerHosts} from '@gonvex/local-runtime/native-bridge';
const hosts = nativeReducerHosts();
export const localRuntime = {...${JSON.stringify(metadata)} as const, create: hosts.create};
export {hosts};\n`;
  const client = `${header}import {GonvexClient as BaseClient, type GonvexClientOptions} from '@gonvex/client';
import {localRuntime} from './local-runtime';
export class GonvexClient extends BaseClient {constructor(url:string, options:GonvexClientOptions={}) {super(url,{...options,localRuntime:options.localRuntime??localRuntime});}}
export {createFirebaseAuthAdapter} from '@gonvex/client';\n`;
  return {
    'client.native.ts': client,
    'client.web.ts': client,
    'local-native-host.json': JSON.stringify({html})+'\n',
    'local-native-binding.ts': shared,
    'local-runtime.native.tsx': `${header}import React, {useSyncExternalStore} from 'react';
import {WebView} from 'react-native-webview';
import {nativeMessageScript, installNativeRuntimeGlobals} from '@gonvex/local-runtime/native-bridge';
import * as ExpoCrypto from 'expo-crypto';
installNativeRuntimeGlobals({getRandomValues:array=>ExpoCrypto.getRandomValues(array),randomUUID:ExpoCrypto.randomUUID});
import host from './local-native-host.json';
import {hosts} from './local-native-binding';
export {localRuntime} from './local-native-binding';
export function LocalRuntimeHost() {
 const bridges = useSyncExternalStore(hosts.subscribe,hosts.snapshot,hosts.snapshot);
 return <>{bridges.map(bridge=><WebView key={bridge.id} source={{html:host.html,baseUrl:'https://gonvex.local.invalid/'}} originWhitelist={['https://gonvex.local.invalid']} style={{position:'absolute',width:1,height:1,opacity:0}} pointerEvents="none" accessible={false} javaScriptEnabled domStorageEnabled={false} setSupportMultipleWindows={false} allowFileAccess={false} onShouldStartLoadWithRequest={request=>request.url==='https://gonvex.local.invalid/'||request.url==='about:blank'} ref={view=>{if(view)bridge.attach(message=>view.injectJavaScript(nativeMessageScript(message)));}} onMessage={event=>bridge.receive(event.nativeEvent.data)} onError={event=>bridge.fail(event.nativeEvent.description)} onContentProcessDidTerminate={()=>bridge.fail('Native Reducer host terminated')} onRenderProcessGone={()=>bridge.fail('Native Reducer host terminated')}/>)}</>;
}
`,
    'local-runtime.web.tsx': `${header}import React, {useSyncExternalStore, useLayoutEffect, useRef} from 'react';
import type {NativeReducerBridge} from '@gonvex/local-runtime/native-bridge';
import host from './local-native-host.json';
import {hosts} from './local-native-binding';
export {localRuntime} from './local-native-binding';
function Host({bridge}:{bridge:NativeReducerBridge}) {
 const frame=useRef<HTMLIFrameElement>(null);
 useLayoutEffect(()=>{const receive=(event:MessageEvent)=>{if(event.source===frame.current?.contentWindow&&typeof event.data==='string')bridge.receive(event.data);};window.addEventListener('message',receive);return()=>window.removeEventListener('message',receive);},[bridge]);
 return <iframe ref={node=>{frame.current=node;if(node)bridge.attach(message=>node.contentWindow?.postMessage(message,'*'));}} title="Gonvex local execution" sandbox="allow-scripts" srcDoc={host.html} style={{display:'none'}}/>;
}
export function LocalRuntimeHost(){const bridges=useSyncExternalStore(hosts.subscribe,hosts.snapshot,hosts.snapshot);return <>{bridges.map(bridge=><Host key={bridge.id} bridge={bridge}/>)}</>;}
`,
  };
}
