import assert from 'node:assert/strict';
import { mkdtemp, mkdir, writeFile, rm, symlink } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import test from 'node:test';
import { build } from 'rolldown';
import { chromium } from '@playwright/test';
import { buildModuleArtifact, moduleManifestFunctions } from '../dist/module-artifact.js';
import { localBindings } from '../dist/local-bindings.js';

test('codegen owns local execution and never replicates unexposed columns', async t => {
  const root = await mkdtemp(join(tmpdir(), 'gonvex-local-bindings-'));
  t.after(() => rm(root, { recursive: true, force: true }));
  await mkdir(join(root, 'gonvex'));
  await mkdir(join(root, 'migrations'));
  await mkdir(join(root, 'node_modules', '@gonvex'), { recursive: true });
  await symlink(fileURLToPath(new URL('../../module-sdk', import.meta.url)), join(root, 'node_modules', '@gonvex', 'module-sdk'));
  await writeFile(join(root, 'migrations', '0000.sql'), 'CREATE TABLE tasks ("_id" text PRIMARY KEY, title text, secret text);');
  await writeFile(join(root, 'gonvex', 'client-contract.json'), JSON.stringify({version: 1, offlineMaxAgeMs: null}));
  const entry = join(root, 'gonvex', 'index.ts');
  await writeFile(entry, `import { reducer, schema, replicaCollection, visibility, action, internalQuery, tenantCron } from '@gonvex/module-sdk';
export const access = visibility({table:'tasks', key:'_id', sets:{}, where:{operator:'public'}});
export const list = replicaCollection({args:schema.object({}),result:schema.any(),replica:{table:'tasks',key:'_id',columns:['_id','title'],mode:'eager',maxRows:100,maxBytes:10000}});
export const get = replicaCollection({args:schema.object({id:schema.string()}),result:schema.any(),replica:{table:'tasks',key:'_id',columns:['_id','title'],equalFilters:{_id:'id'},mode:'eager',maxRows:1,maxBytes:1000}});
export const rename = reducer({args:schema.object({id:schema.string(),title:schema.string()}),result:schema.any(),run:(ctx,args)=>ctx.db.update('tasks',args.id,{title:args.title})});
export const external = action({args:schema.object({}),result:schema.any(),run:()=>{throw new Error('EXTERNAL_ACTION_MUST_NOT_SHIP')}});
export const serverRead = internalQuery({description:'INTERNAL_QUERY_MUST_NOT_SHIP',args:schema.object({}),result:schema.any(),liveQueryPlan:{table:'tasks',key:'_id',columns:['_id','title']}});
export const scheduled = tenantCron({name:'SERVER_CRON_MUST_NOT_SHIP',expression:'*/5 * * * *',function:'external',args:{}});
`);
  const module = await buildModuleArtifact({root,backendDir:join(root,'gonvex'),files:[entry],migrations:[]});
  assert.deepEqual(JSON.parse(Buffer.from(module.files['client-contract.json'], 'base64').toString()), {version: 1, offlineMaxAgeMs: null});
  const functions = moduleManifestFunctions(module);
  assert.equal(functions.rename.localExecution, 1);
  assert.equal(functions.rename.offline.mode, 'allowed');
  assert.deepEqual(functions['__local.tasks'].replica.columns, ['_id','title']);
  assert.equal(functions['__local.tasks'].replica.maxRows, 100);
  assert.equal(functions['__local.tasks'].replica.maxBytes, 10000);
  assert.equal(functions.external.localExecution, undefined);
  const generated = await localBindings(root, {module,functions});
  assert.match(generated['local-executor.ts'], /createPortableReducer/);
  assert.match(generated['local-runtime.native.tsx'], /installNativeRuntimeGlobals/);
  assert.equal(generated['local-worker.ts'], undefined);
  assert.deepEqual(JSON.parse(generated['local-native-host.json']), {});
  for (const [name, source] of Object.entries(generated)) {
    if (name.endsWith('.js')) assert.doesNotMatch(source, /EXTERNAL_ACTION_MUST_NOT_SHIP|INTERNAL_QUERY_MUST_NOT_SHIP|SERVER_CRON_MUST_NOT_SHIP/);
    await writeFile(join(root, 'gonvex', name), source);
  }
  assert.ok(Object.keys(generated).some(name => /^local-reducer-.+\.js$/.test(name)), 'web Reducers must retain module boundaries');
  const bundled = await import(pathToFileURL(join(root, 'gonvex', 'local-reducers.js')).href);
  assert.match(generated['local-reducers.js'], /import\(/);
  assert.doesNotMatch(generated['local-reducers.js'], /ctx\.db\.update/);
  const writes = [];
  await (await bundled.localReducers.rename()).handler({db:{update:(...args)=>writes.push(args)}},{id:'t',title:'changed'});
  assert.deepEqual(writes, [['tasks','t',{title:'changed'}]]);
  // Execute the generated shared body offline in a real browser, with no
  // worker, hidden WebView or WebAssembly engine in its dependency graph.
  await symlink(fileURLToPath(new URL('../../local-runtime', import.meta.url)), join(root, 'node_modules', '@gonvex', 'local-runtime'));
  for (const [name, source] of Object.entries(generated)) await writeFile(join(root, 'gonvex', name), source);
  const output = await build({input:join(root,'gonvex','local-executor.ts'),platform:'browser',write:false,output:{format:'iife',name:'SharedExecutor',codeSplitting:false}});
  const code = output.output.find(chunk=>chunk.type==='chunk').code;
  assert.doesNotMatch(code,/PGlite|new Worker|WebAssembly\.instantiate/);
  const browser = await chromium.launch({headless:true,args:['--no-sandbox']});
  t.after(()=>browser.close());
  const context = await browser.newContext({offline:true});
  const page = await context.newPage();
  const requests = [];
  page.on('request', request=>requests.push(request.url()));
  await page.addScriptTag({content:code});
  const response=await page.evaluate(async hash=>SharedExecutor.localRuntime.create().execute('rename',{id:'t',title:'changed'},{scope:'scope',tables:{tasks:{complete:true,rows:[{_id:'t',title:'old'}]}}},{scope:'scope',commandId:'intent',now:1,artifactHash:hash,identity:{auth:{account:{id:'account'}},tenant:{id:'tenant'},member:{id:'member',accountId:'account',permissions:{}}}}),module.hash);
  assert.equal(response.patches[0].fields.title,'changed');
  assert.deepEqual(requests,[], 'shared execution must not download an engine or contact a server');
});
